import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ToDo Sentinel',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`flex flex-col bg-slate-200 dark:bg-slate-950 text-slate-950 dark:text-slate-200 min-h-screen ${inter.className} w-full`}>
        <main className='px-4 py-4 flex flex-1 w-full'>
          {children}
        </main>
      </body>
    </html>
  )
};
